# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yapf pytest
    - name: Install dependencies for testing
      run: |
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
#    - name: Lint with yapf
#      run: |
#        yapf -r --diff .
    - name: Lint with black
      run: |
        black --check .
    - name: Test hw1
      run: |
        cd hw1
        python -m pytest
    - name: Test hw3
      run: |
        cd hw3
        python -m unittest test.py
    - name: Test hw4
      run: |
        cd hw4
        pip install -r requirements.txt
        docker-compose up -d
        python -m unittest test.py
    - name: Test hw5
      run: |
        cd hw5
        docker-compose up --abort-on-container-exit --exit-code-from tests